
// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants 
{
    public static final class DrivetrainConstants
    {
        //Arcade Drive
        public static final double DEFAULT_JOYSTICK_DEADBAND = 0.15;
        public static final double DEFAULT_FORZA_DEADBAND = 0.01;
        public static final double DEFAULT_ARCADE_JOY_DEADBAND = 0.01;
        public static final boolean DEFAULT_FORZA_MODE = true;
        
        public static final int LEFT_LEAD_TALON_CAN_ID = 0;
        public static final int LEFT_FOLLOWER_TALON_CAN_ID = 1;
        public static final int RIGHT_LEAD_TALON_CAN_ID = 2;
        public static final int RIGHT_FOLLOWER_TALON_CAN_ID = 3;
        public static final double KF = 0;
        public static final double KP = 9e-5;
        public static final double KI = 0.0;
        public static final double KD = 0.0;
        public static final int PID_SLOT_ID = 0;
        public static final int PID_CONFIG_TIMEOUT_MS = 10;
        public static final int CONFIG_FEEDBACKSENSOR_TIMEOUT_MS = 4000;
        public static final double CLOSED_LOOP_RAMP = 0.5;
        public static final double MAX_VELOCITY = 5900; 
        public static final double DEFAULT_MAX_VELOCITY_PERCENTAGE = 1.0;
        public static final double DEFAULT_MAX_TURNING_SPEED = 0.85;
        public static final double VELOCITY_SLOWDOWN_MODIFIER = 0.5;
        public static final double MIN_VELOCITY = 0;
        public static final double MAX_ACCEL = 2000;
        public static final int SMART_MOTION_SLOT = 0;
        public static final double MIN_OUTPUT = -1;
        public static final double ENCODER_CONVERSION_FACTOR = 1.0;
        public static final double MAX_OUTPUT = 1;

        //MISC
        public static final double WHEEL_CIRCUMFERENCE_FEET = (4.0d/12.0d)*Math.PI; // Wheel diameter 3 in, converting to feet
        public static final double SECONDS_TO_MINUTES = 1.0d/60.0d;
        public static final double MINUTES_TO_SECONDS = 60.0d/1.0d;
        public static final double GEARBOX_RATIO_TO_ONE = 6.67d;
        public static final int ENCODER_COUNTS_PER_REVOLUTION = 4096;
        public static final int ENCODER_EDGES_PER_STEP =  1; 
        public static final int ENCODER_UNITS_PER_REVOLUTION = ENCODER_COUNTS_PER_REVOLUTION; // Edges per Rotation
        public static final double TRACK_WIDTH_FEET = 24.831d/12.0d; //Track width is 24.831 inches
        public static final boolean USE_NAVX_HEADING = true; 
    }

    public static final class SmoothControlConstants
    {
        public static final double K1 = 1.0d;
        public static final double K2 = 3.0d;
    }

    public static final class AutonomousCommandConstants
    {
        public static final double TARGET_WITHIN_RANGE_FEET = DrivetrainConstants.TRACK_WIDTH_FEET/4.0d; //Quarter track width
        public static final double STARTING_X = 0.0d;
        public static final double STARTING_Y = 0.0d;
        public static final double STARTING_HEADING = Math.toRadians(0.0d);
    }

    public static final class InputConstants 
    {
        public static final double DRIVE_JOYSTICK_DEADBAND = 0.0;
        public static final double ARCADE_JOY_DEADBAND = 0.0;
        public static final double FORZA_DEADBAND = 0.0;
        public static final boolean DEFAULT_FORZA_MODE = true;
    }
}
